/**
 * In-product systemd autostart for the Linux player.
 *
 * Boot launch on Linux is two separate things, and only one of them is ours:
 *
 *   1. A graphical session exists after boot (auto-login, a kiosk compositor,
 *      display-manager configuration). This is root-owned OS setup. The player
 *      cannot install it and does not try.
 *   2. The player starts inside that session and restarts after any exit. This
 *      is a systemd *user* unit under `~/.config/systemd/user`, which the kiosk
 *      user owns outright — no root, no polkit, no third-party tooling.
 *
 * This module owns (2), and reports honestly about (1) rather than claiming a
 * success it cannot verify. The installer is deliberately better-informed than
 * the hand-written unit in `deploy/tilecast-player.service`: a running player
 * knows its own `$APPIMAGE`, its real `DISPLAY`/`WAYLAND_DISPLAY`, its data
 * directory, and whether `graphical-session.target` is actually reachable in
 * this session — all of which the operator otherwise has to guess, and which
 * are the usual reasons a hand-installed unit is enabled but never starts.
 *
 * Two invariants worth stating, because both are load-bearing:
 *
 * - Install never starts the unit. The player issuing the command *is* the
 *   player the unit supervises; `enable --now` would run a second copy over the
 *   first. The unit takes effect at the next boot or session start, which is
 *   exactly what it is for.
 * - Remove never stops the unit, and refuses to delete a unit file this module
 *   did not write (identified by the generated marker). Removing autostart is a
 *   decommissioning step, not a way to kill a running screen, and an operator's
 *   hand-tuned unit is not ours to throw away.
 */

import { execFile } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { logger } from "./log";

const log = logger("autostart");

/** Unit name, fixed so install/remove/probe agree without persisted state. */
export const UNIT_NAME = "tilecast-player.service";

/**
 * Marker written into every generated unit. `remove` requires it, so a unit an
 * operator wrote or edited by hand is left alone.
 */
export const GENERATED_MARKER =
  "# Generated by Tilecast Player (install_autostart).";

/**
 * A legacy AppImage runtime can leave its FUSE mount behind when the launcher
 * fails before Electron starts. Run this before every supervised start so the
 * normal systemd restart loop can recover without requiring an operator to
 * unmount the stale directory first.
 *
 * The command is deliberately narrower than `rm -rf /tmp/.mount_*`: it only
 * considers mountpoints in AppImage's temporary namespace, only accepts FUSE
 * filesystems, and removes a directory only after an unmount attempt. Every
 * operation is best-effort so a missing optional utility never prevents the
 * FUSE-independent `--appimage-extract-and-run` path from starting.
 */
export const FUSE_RECOVERY_COMMAND =
  "command -v findmnt >/dev/null 2>&1 || exit 0; " +
  "findmnt -rn -o TARGET,FSTYPE | while read -r mountpoint fstype; do " +
  'case "$mountpoint:$fstype" in /tmp/.mount_*:fuse*) ' +
  'fusermount3 -uz "$mountpoint" 2>/dev/null || ' +
  'fusermount -uz "$mountpoint" 2>/dev/null || ' +
  'umount -l "$mountpoint" 2>/dev/null || true; ' +
  'rmdir "$mountpoint" 2>/dev/null || true;; esac; ' +
  "done";

/**
 * The install target, chosen from what this session actually provides rather
 * than assumed. `graphical-session.target` is correct on a desktop session and
 * ties the player's lifetime to the session; minimal compositor sessions
 * frequently never reach it, and a unit wanted by a target that never activates
 * is enabled and silently dead — the single most common autostart failure.
 */
export type AutostartTarget = "graphical-session.target" | "default.target";

/** What the device believes about its own autostart, as reported to Studio. */
export type AutostartState =
  | "unknown"
  /** systemd user manager is present and no generated unit is installed. */
  | "not_installed"
  /** A generated unit is installed and enabled. */
  | "installed"
  /** A unit file exists but is not enabled, or was written by hand. */
  | "needs_attention"
  /** Not a managed AppImage, or no systemd user manager: cannot be installed. */
  | "unsupported";

export interface AutostartStatus {
  state: AutostartState;
  /** Whether *this* process was started by systemd (INVOCATION_ID is set). */
  supervised: boolean;
  target: AutostartTarget | null;
  /** Whether the user manager persists across logout (`loginctl enable-linger`). */
  lingerEnabled: boolean;
  /** Short diagnostic for the state, surfaced in Studio. Empty when healthy. */
  detail: string;
}

export interface CommandOutput {
  code: number;
  stdout: string;
  stderr: string;
}

export interface AutostartDeps {
  /** The running AppImage path (process.env.APPIMAGE), or null when unpackaged. */
  appImagePath: string | null;
  /** Absolute path of `~/.config/systemd/user`. */
  unitDirectory: string;
  /** UID (or user name) to ask loginctl about; empty when it cannot be read. */
  userIdentifier: string;
  /**
   * Environment facts captured from the live session. These are what make a
   * generated unit more accurate than a hand-written one.
   */
  environment: {
    display: string | null;
    waylandDisplay: string | null;
    /** Set by systemd for its own children; proof this process is supervised. */
    invocationId: string | null;
    /** Non-default state directory, which the unit must preserve. */
    dataDirectory: string | null;
    /** Server URL supplied by environment rather than persisted setup. */
    serverUrl: string | null;
    logLevel: string | null;
  };
  /** Run a command to completion. Must not throw for a non-zero exit. */
  run(command: string, args: string[]): Promise<CommandOutput>;
  readFile(path: string): Promise<string | null>;
  writeFile(path: string, contents: string): Promise<void>;
  removeFile(path: string): Promise<void>;
  makeDirectory(path: string): Promise<void>;
}

/**
 * Quote a systemd unit value when it contains whitespace or quotes. Unquoted
 * values with spaces are split into arguments, which would silently truncate an
 * ExecStart path or an environment value.
 *
 * Control characters are dropped rather than quoted. Unit files are line-based:
 * a newline ends the directive even inside quotes, so a value carrying one would
 * turn the rest of itself into a new directive. Nothing legitimate here — a
 * display name, a URL, an AppImage path — contains one.
 */
export function unitQuote(value: string): string {
  const safe = value.replace(/[\p{Cc}]/gu, "");
  if (!/[\s"'\\]/.test(safe)) {
    return safe;
  }
  return `"${safe.replace(/(["\\])/g, "\\$1")}"`;
}

export interface UnitRenderInput {
  appImagePath: string;
  target: AutostartTarget;
  environment: AutostartDeps["environment"];
}

/**
 * Render the unit file. Pure, so the exact text is a test fixture rather than
 * something only observable on a real device.
 *
 * `StartLimitIntervalSec=0` belongs in `[Unit]` on modern systemd (it is
 * ignored under `[Service]`), and it is what keeps a crash loop backing off on
 * RestartSec forever instead of latching into `failed` — a latched unit is a
 * dark screen until someone visits it.
 */
export function renderUnit(input: UnitRenderInput): string {
  const { appImagePath, target, environment } = input;
  const lines: string[] = [
    GENERATED_MARKER,
    "#",
    "# Values below were captured from the running player, not guessed. Edit",
    "# freely: once this marker is removed or changed, Tilecast will not",
    "# overwrite or delete this file.",
    "",
    "[Unit]",
    "Description=Tilecast Player",
    `After=${target} network.target`,
  ];
  if (target === "graphical-session.target") {
    // Tie the player's lifetime to the graphical session it renders into. On a
    // default.target install there is no session to be part of.
    lines.push(`PartOf=${target}`);
  }
  lines.push(
    "StartLimitIntervalSec=0",
    "",
    "[Service]",
    "Type=simple",
    // A failed legacy runtime can leave a FUSE mount behind before Electron
    // starts. Clean only stale AppImage FUSE mountpoints before retrying.
    `ExecStartPre=/bin/sh -c ${unitQuote(FUSE_RECOVERY_COMMAND)}`,
    // Extract-and-run is a runtime mode, not a manually unpacked installation.
    // It preserves APPIMAGE for signed updates and starts even when mounting is
    // unavailable, including legacy artifacts that still depend on FUSE 2.
    `ExecStart=${unitQuote(appImagePath)} --appimage-extract-and-run`,
    "Restart=always",
    "RestartSec=5",
  );

  const environmentLines: Array<[string, string | null]> = [
    ["TILECAST_LOG_LEVEL", environment.logLevel ?? "info"],
    // Without the data directory the restarted unit would read a different
    // state directory and present itself as an unpaired screen.
    ["TILECAST_DATA_DIR", environment.dataDirectory],
    ["TILECAST_SERVER_URL", environment.serverUrl],
    ["DISPLAY", environment.display],
    ["WAYLAND_DISPLAY", environment.waylandDisplay],
  ];
  for (const [name, value] of environmentLines) {
    if (value) {
      lines.push(`Environment=${unitQuote(`${name}=${value}`)}`);
    }
  }

  lines.push("", "[Install]", `WantedBy=${target}`, "");
  return lines.join("\n");
}

/**
 * Whether a unit bypasses AppImage's FUSE mount path. Keep this check strict:
 * the command-line switch predates the equivalent environment variable and is
 * therefore the portable recovery path for Tilecast's older AppImages.
 */
export function hasFuseIndependentLaunch(contents: string): boolean {
  return /^ExecStart=.*(?:^|\s)--appimage-extract-and-run(?:\s|$)/m.test(
    contents,
  );
}

function usesLegacyDirectAppImageLaunch(contents: string): boolean {
  return /^ExecStart=.*\.AppImage(?:\s|$)/m.test(contents);
}

export class AutostartInstaller {
  constructor(private readonly deps: AutostartDeps) {}

  private unitPath(): string {
    return `${this.deps.unitDirectory}/${UNIT_NAME}`;
  }

  private get supervised(): boolean {
    return Boolean(this.deps.environment.invocationId);
  }

  /** Whether a systemd user manager is reachable at all. */
  private async hasUserManager(): Promise<boolean> {
    try {
      const result = await this.deps.run("systemctl", [
        "--user",
        "show",
        "--property=Version",
      ]);
      return result.code === 0;
    } catch {
      return false;
    }
  }

  private async isEnabled(): Promise<boolean> {
    try {
      const result = await this.deps.run("systemctl", [
        "--user",
        "is-enabled",
        UNIT_NAME,
      ]);
      return result.stdout.trim() === "enabled";
    } catch {
      return false;
    }
  }

  private async lingerEnabled(): Promise<boolean> {
    if (!this.deps.userIdentifier) {
      return false;
    }
    try {
      // Read-only; needs no privilege. Root is only required to *change* it.
      // The user must be named: `show-user` with no argument reports the
      // login manager's own properties, which have no Linger at all, so an
      // unnamed call answers "no" for every device.
      const result = await this.deps.run("loginctl", [
        "show-user",
        this.deps.userIdentifier,
        "--property=Linger",
        "--value",
      ]);
      return result.code === 0 && result.stdout.trim() === "yes";
    } catch {
      return false;
    }
  }

  /**
   * Pick the install target from what the session provides. Preferring an
   * inactive `graphical-session.target` would produce a unit that is enabled
   * and never starts, so an unreachable target falls back to `default.target`,
   * which the user manager activates on its own.
   */
  private async chooseTarget(): Promise<AutostartTarget> {
    try {
      const result = await this.deps.run("systemctl", [
        "--user",
        "is-active",
        "graphical-session.target",
      ]);
      if (result.stdout.trim() === "active") {
        return "graphical-session.target";
      }
    } catch {
      // Fall through to the safe target.
    }
    return "default.target";
  }

  private async readGeneratedUnit(): Promise<string | null> {
    const contents = await this.deps.readFile(this.unitPath());
    if (contents === null) {
      return null;
    }
    return contents.includes(GENERATED_MARKER) ? contents : null;
  }

  private targetFromUnit(contents: string): AutostartTarget | null {
    if (contents.includes("WantedBy=graphical-session.target")) {
      return "graphical-session.target";
    }
    if (contents.includes("WantedBy=default.target")) {
      return "default.target";
    }
    return null;
  }

  /**
   * Upgrade an older Tilecast-owned unit after any successful player launch.
   *
   * This is intentionally not a general install: a missing unit still needs an
   * explicit install_autostart command, and an operator-owned unit is never
   * changed. It only closes the upgrade gap where an old generated ExecStart
   * would put the screen back into a FUSE-dependent crash loop on its next
   * restart.
   */
  async repairLegacyGeneratedUnit(): Promise<boolean> {
    const existing = await this.deps.readFile(this.unitPath());
    if (
      existing === null ||
      !existing.includes(GENERATED_MARKER) ||
      hasFuseIndependentLaunch(existing) ||
      !this.deps.appImagePath
    ) {
      return false;
    }

    try {
      const target = this.targetFromUnit(existing) ?? (await this.chooseTarget());
      await this.deps.writeFile(
        this.unitPath(),
        renderUnit({
          appImagePath: this.deps.appImagePath,
          target,
          environment: this.deps.environment,
        }),
      );
      const reload = await this.deps.run("systemctl", [
        "--user",
        "daemon-reload",
      ]);
      if (reload.code !== 0) {
        log.warn("legacy autostart unit rewritten but daemon-reload failed", {
          error: reload.stderr.trim().slice(0, 160),
        });
        return false;
      }
      log.info("legacy autostart unit upgraded to FUSE-independent launch", {
        target,
      });
      return true;
    } catch (err) {
      log.warn("legacy autostart unit upgrade failed", {
        error: String(err).slice(0, 240),
      });
      return false;
    }
  }

  /** Current autostart facts for the heartbeat. Never throws. */
  async probe(): Promise<AutostartStatus> {
    const base: AutostartStatus = {
      state: "unknown",
      supervised: this.supervised,
      target: null,
      lingerEnabled: false,
      detail: "",
    };
    try {
      if (!this.deps.appImagePath) {
        return {
          ...base,
          state: "unsupported",
          detail: "player is not running as a managed AppImage",
        };
      }
      if (!(await this.hasUserManager())) {
        return {
          ...base,
          state: "unsupported",
          detail: "no systemd user manager on this device",
        };
      }
      const lingerEnabled = await this.lingerEnabled();
      const existing = await this.deps.readFile(this.unitPath());
      if (existing === null) {
        return { ...base, state: "not_installed", lingerEnabled };
      }
      const generated = existing.includes(GENERATED_MARKER);
      const enabled = await this.isEnabled();
      if (!enabled) {
        return {
          ...base,
          state: "needs_attention",
          lingerEnabled,
          target: this.targetFromUnit(existing),
          detail: "unit file present but not enabled",
        };
      }
      if (
        !hasFuseIndependentLaunch(existing) &&
        (generated || usesLegacyDirectAppImageLaunch(existing))
      ) {
        return {
          ...base,
          state: "needs_attention",
          lingerEnabled,
          target: this.targetFromUnit(existing),
          detail: generated
            ? "Tilecast unit still launches through the legacy FUSE mount path"
            : "operator-managed unit launches through the legacy FUSE mount path",
        };
      }
      return {
        ...base,
        state: "installed",
        lingerEnabled,
        target: this.targetFromUnit(existing),
        detail: generated ? "" : "unit was not generated by Tilecast",
      };
    } catch (err) {
      return { ...base, detail: String(err).slice(0, 240) };
    }
  }

  /**
   * Install and enable the unit. Returns a command result for Studio.
   *
   * Never starts the unit: this process is the one it supervises.
   */
  async install(): Promise<{
    success: boolean;
    code: string;
    message: string;
  }> {
    if (!this.deps.appImagePath) {
      return {
        success: false,
        code: "autostart_unsupported",
        message:
          "Player is not running as a managed AppImage; autostart applies to AppImage installations.",
      };
    }
    if (!(await this.hasUserManager())) {
      return {
        success: false,
        code: "autostart_unsupported",
        message:
          "No systemd user manager is available on this device; install autostart with the platform's own mechanism.",
      };
    }

    const existing = await this.deps.readFile(this.unitPath());
    if (existing !== null && !existing.includes(GENERATED_MARKER)) {
      // An operator's own unit outranks ours; overwriting it could discard
      // hand-tuned display, environment, or dependency settings.
      return {
        success: false,
        code: "autostart_conflict",
        message: `A unit at ${this.unitPath()} was not generated by Tilecast and was left unchanged.`,
      };
    }

    try {
      const target = await this.chooseTarget();
      await this.deps.makeDirectory(this.deps.unitDirectory);
      await this.deps.writeFile(
        this.unitPath(),
        renderUnit({
          appImagePath: this.deps.appImagePath,
          target,
          environment: this.deps.environment,
        }),
      );

      const reload = await this.deps.run("systemctl", [
        "--user",
        "daemon-reload",
      ]);
      if (reload.code !== 0) {
        return {
          success: false,
          code: "autostart_failed",
          message: `daemon-reload failed: ${reload.stderr.trim().slice(0, 160)}`,
        };
      }
      // Deliberately not `--now`: see the module comment.
      const enable = await this.deps.run("systemctl", [
        "--user",
        "enable",
        UNIT_NAME,
      ]);
      if (enable.code !== 0) {
        return {
          success: false,
          code: "autostart_failed",
          message: `enable failed: ${enable.stderr.trim().slice(0, 160)}`,
        };
      }
      if (!(await this.isEnabled())) {
        return {
          success: false,
          code: "autostart_failed",
          message:
            "Unit was written but systemd does not report it as enabled.",
        };
      }

      log.info("autostart unit installed", { target });
      return {
        success: true,
        code: "autostart_installed",
        message: this.installMessage(target, await this.lingerEnabled()),
      };
    } catch (err) {
      return {
        success: false,
        code: "autostart_failed",
        message: String(err).slice(0, 240),
      };
    }
  }

  /**
   * Say plainly what the install does and does not guarantee. The player owns
   * "restarts forever, starts with the session"; it cannot own "a graphical
   * session exists after boot", and reporting an unqualified success would
   * misrepresent a screen that will come up dark.
   */
  private installMessage(
    target: AutostartTarget,
    lingerEnabled: boolean,
  ): string {
    if (target === "graphical-session.target") {
      return "Installed and enabled; the player starts with the graphical session and restarts after any exit. Confirm the session itself auto-starts at boot (auto-login or a kiosk compositor).";
    }
    const linger = lingerEnabled
      ? "Lingering is enabled"
      : "Lingering is off, so run `loginctl enable-linger` as root";
    return `Installed and enabled against default.target because graphical-session.target is not active in this session. ${linger}, and confirm a graphical session (auto-login or a kiosk compositor) starts at boot.`;
  }

  /**
   * Disable and delete a generated unit. Never stops the running player, and
   * never deletes a unit it did not write.
   */
  async remove(): Promise<{
    success: boolean;
    code: string;
    message: string;
  }> {
    const generated = await this.readGeneratedUnit();
    if (generated === null) {
      const existing = await this.deps.readFile(this.unitPath());
      if (existing === null) {
        return {
          success: true,
          code: "autostart_absent",
          message: "No Tilecast-generated autostart unit is installed.",
        };
      }
      return {
        success: false,
        code: "autostart_conflict",
        message: `The unit at ${this.unitPath()} was not generated by Tilecast and was left unchanged.`,
      };
    }
    try {
      // Disable only: stopping the unit would terminate the player that is
      // executing this command.
      await this.deps.run("systemctl", ["--user", "disable", UNIT_NAME]);
      await this.deps.removeFile(this.unitPath());
      await this.deps.run("systemctl", ["--user", "daemon-reload"]);
      log.info("autostart unit removed");
      return {
        success: true,
        code: "autostart_removed",
        message:
          "Autostart disabled and removed. The running player is unaffected and will not return after the next restart.",
      };
    } catch (err) {
      return {
        success: false,
        code: "autostart_failed",
        message: String(err).slice(0, 240),
      };
    }
  }
}

/**
 * Whether this process looks like it was launched by the boot sequence rather
 * than by hand: started by systemd, and started close enough to system boot
 * that no operator could have been involved.
 *
 * This is the Linux answer to the Android boot receiver's verification. It is
 * evidence, not proof — which is why it requires both facts, and why a manual
 * `systemctl --user start` minutes into a session does not qualify.
 */
export function coldBootLaunchVerified(input: {
  supervised: boolean;
  /** Seconds the system had been up when this process started. */
  systemUptimeSecondsAtStart: number | null;
}): boolean {
  if (!input.supervised || input.systemUptimeSecondsAtStart === null) {
    return false;
  }
  return input.systemUptimeSecondsAtStart <= COLD_BOOT_WINDOW_SECONDS;
}

/**
 * How long after boot a launch still counts as "at boot". Generous enough for a
 * slow display manager, a disk check, or a compositor that takes its time on
 * 2012-era hardware; short enough that a hand-started player does not qualify.
 */
export const COLD_BOOT_WINDOW_SECONDS = 300;

/** Longest any single systemctl/loginctl probe may take before it is abandoned. */
const COMMAND_TIMEOUT_MS = 10_000;

/**
 * Real-device dependencies. Kept here rather than in the runtime so the
 * orchestrator composes one object and every process/filesystem detail stays
 * next to the logic it serves.
 */
export function systemAutostartDeps(
  environment: NodeJS.ProcessEnv = process.env,
): AutostartDeps {
  return {
    appImagePath: environment["APPIMAGE"] ?? null,
    unitDirectory: `${environment["HOME"] ?? homedir()}/.config/systemd/user`,
    userIdentifier: String(process.getuid?.() ?? environment["USER"] ?? ""),
    environment: {
      display: environment["DISPLAY"] ?? null,
      waylandDisplay: environment["WAYLAND_DISPLAY"] ?? null,
      invocationId: environment["INVOCATION_ID"] ?? null,
      dataDirectory: environment["TILECAST_DATA_DIR"] ?? null,
      serverUrl: environment["TILECAST_SERVER_URL"] ?? null,
      logLevel: environment["TILECAST_LOG_LEVEL"] ?? null,
    },
    // Resolves for a non-zero exit as well: a failed probe is an answer
    // ("not enabled", "no user manager"), not an exception.
    run: (command, args) =>
      new Promise((resolve, reject) => {
        execFile(
          command,
          args,
          { timeout: COMMAND_TIMEOUT_MS, encoding: "utf8" },
          (error, stdout, stderr) => {
            if (error && typeof error.code !== "number") {
              reject(error);
              return;
            }
            resolve({
              code: typeof error?.code === "number" ? error.code : 0,
              stdout: stdout ?? "",
              stderr: stderr ?? "",
            });
          },
        );
      }),
    readFile: async (path) => {
      try {
        return await readFile(path, "utf8");
      } catch {
        return null;
      }
    },
    writeFile: (path, contents) => writeFile(path, contents, { mode: 0o644 }),
    removeFile: (path) => rm(path, { force: true }),
    makeDirectory: async (path) => {
      await mkdir(path, { recursive: true, mode: 0o700 });
    },
  };
}

/**
 * Seconds of system uptime from the contents of `/proc/uptime`, or null when
 * the file is missing or unparseable (a non-Linux host, or a container without
 * a procfs). Callers treat null as "no boot evidence" rather than as zero.
 */
export function parseProcUptime(contents: string): number | null {
  const seconds = Number.parseFloat(contents.trim().split(/\s+/)[0] ?? "");
  return Number.isFinite(seconds) && seconds >= 0 ? seconds : null;
}
