import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router";
import { Download } from "lucide-react";
import { ActivityPagination, activityParams, activityRequest, AuditPage, EmptyState, ErrorNotice, EventPage, formatDuration, formatWhen, humanize, Loading, ProofPage, ProofSummary, ResourceLink, ResultBadge, TechnicalDetails, useActivityCursor } from "./ActivityShared";

export function ProofTab({ range, filters, canExport, dimension, setDimension }: { range: { from: string; to: string }; filters: Record<string, string>; canExport: boolean; dimension: string; setDimension: (value: string) => void }) {
  const params = activityParams(range, filters);
  const pagination = useActivityCursor(params.toString());
  const pageParams = new URLSearchParams(params);
  if (pagination.cursor) pageParams.set("cursor", pagination.cursor);
  const query = useQuery({ queryKey: ["activity", "proof", pageParams.toString()], queryFn: () => activityRequest<ProofPage>(`/proof-of-play?${pageParams}`) });
  const summaryParams = new URLSearchParams(params); summaryParams.set("dimension", dimension);
  const summary = useQuery({ queryKey: ["activity", "proof-summary", summaryParams.toString()], queryFn: () => activityRequest<ProofSummary>(`/proof-of-play/summary?${summaryParams}`) });
  if (query.isLoading) return <Loading />;
  if (query.error) return <ErrorNotice error={query.error} />;
  return <>
    <section className="activity-panel activity-proof-summary"><header><div><h3>Proof-of-play summary</h3><p>Only Player-confirmed intervals count toward coverage.</p></div><div className="activity-panel-actions"><select value={dimension} onChange={(e) => setDimension(e.target.value)}><option value="screen">By screen</option><option value="content">By content</option><option value="presentation">By Playlist or Layout</option><option value="schedule">By schedule</option></select>{canExport && <a className="button button--secondary" href={`/api/v1/activity/proof-of-play/export.csv?${params}`}><Download size={15} /> Export CSV</a>}</div></header><div className="activity-summary-table">{summary.data?.items.slice(0, 12).map((item) => <div key={item.key}><span><strong>{item.label}</strong><small>{item.records} confirmed records</small></span><span>{formatDuration(item.confirmedDurationMs)}</span><span>{item.coveragePercent.toFixed(0)}% coverage</span><span>{item.failures} failures</span></div>)}</div></section>
    <section className="activity-panel"><header><div><h3>Detailed proof of play</h3><p>What was actually displayed, where, when, and for how long.</p></div></header><div className="activity-table-wrap"><table className="activity-table"><thead><tr><th>Started</th><th>Screen</th><th>Presentation</th><th>Content</th><th>Duration</th><th>Result</th><th>Context</th><th>Details</th></tr></thead><tbody>{query.data?.items.map((item) => <tr key={item.id}><td><time>{formatWhen(item.startedAt)}</time></td><td><Link to={`/screens/${item.screenId}?tab=activity`}>{item.screenName}</Link><small>{item.groupName}</small></td><td><strong><ResourceLink type={item.presentationType} id={item.presentationId} label={item.presentationName || item.presentationId || "—"} /></strong><small>{[item.presentationType, item.presentationRevision && `rev ${item.presentationRevision}`].filter(Boolean).join(" · ")}</small></td><td><strong><ResourceLink type={item.contentType} id={item.contentId} label={item.contentName || item.contentId || "Root presentation"} /></strong><small>{item.contentType}</small></td><td>{item.actualDurationMs == null ? "In progress" : formatDuration(item.actualDurationMs)}</td><td><ResultBadge value={item.result} /></td><td><small>{item.trigger || "—"}{item.scheduleId ? ` · schedule ${item.scheduleId}` : ""}</small></td><td><TechnicalDetails value={{ manifestVersion: item.manifestVersion, failureCode: item.failureCode, playlistItemId: item.playlistItemId, layoutPlacementId: item.layoutPlacementId, sourceId: item.sourceId, selectedRecordId: item.selectedRecordId, selectionDate: item.selectionDate, sourceCachedAt: item.sourceCachedAt, sourceRevision: item.sourceRevision, snapshotHash: item.snapshotHash, ...item.details }} /></td></tr>)}</tbody></table></div>{!query.data?.items.length && <EmptyState message="No Player-confirmed playback was reported in this range." />}<ActivityPagination pagination={pagination} nextCursor={query.data?.nextCursor} /></section>
  </>;
}

export function EventsTab({ range, filters }: { range: { from: string; to: string }; filters: Record<string, string> }) {
  const params = activityParams(range, filters); const pagination = useActivityCursor(params.toString()); const pageParams = new URLSearchParams(params); if (pagination.cursor) pageParams.set("cursor", pagination.cursor);
  const query = useQuery({ queryKey: ["activity", "events", pageParams.toString()], queryFn: () => activityRequest<EventPage>(`/screen-events?${pageParams}`), refetchInterval: 20_000 });
  if (query.isLoading) return <Loading />; if (query.error) return <ErrorNotice error={query.error} />;
  return <section className="activity-panel"><header><div><h3>Screen Events</h3><p>Technical state transitions and meaningful Player or server activity. Routine successful heartbeats are excluded.</p></div></header><div className="activity-table-wrap"><table className="activity-table"><thead><tr><th>Severity</th><th>Time</th><th>Screen</th><th>Event</th><th>Related resource</th><th>Result</th><th>Details</th></tr></thead><tbody>{query.data?.items.map((item) => <tr key={item.id}><td><ResultBadge value={item.severity} /></td><td><time>{formatWhen(item.timestamp)}</time><small>Received {formatWhen(item.receivedAt)}</small></td><td><Link to={`/screens/${item.screenId}?tab=activity`}>{item.screenName}</Link><small>{item.groupName}</small></td><td><strong>{humanize(item.eventType)}</strong><small>{item.category} · seq {item.sequence ?? "server"}</small></td><td>{item.relatedId ? <><strong><ResourceLink type={item.relatedType} id={item.relatedId} label={item.relatedId} /></strong><small>{item.relatedType}</small></> : "—"}</td><td><ResultBadge value={item.result} /></td><td><TechnicalDetails value={{ failureCode: item.failureCode, failureMessage: item.failureMessage, manifestVersion: item.manifestVersion, ...item.details }} /></td></tr>)}</tbody></table></div>{!query.data?.items.length && <EmptyState message="No technical screen events matched these filters." />}<ActivityPagination pagination={pagination} nextCursor={query.data?.nextCursor} /></section>;
}

export function AuditTab({ range, filters, canExport }: { range: { from: string; to: string }; filters: Record<string, string>; canExport: boolean }) {
  const params = activityParams(range, filters); const pagination = useActivityCursor(params.toString()); const pageParams = new URLSearchParams(params); if (pagination.cursor) pageParams.set("cursor", pagination.cursor);
  const query = useQuery({ queryKey: ["activity", "audit", pageParams.toString()], queryFn: () => activityRequest<AuditPage>(`/audit?${pageParams}`) });
  if (query.isLoading) return <Loading />; if (query.error) return <ErrorNotice error={query.error} />;
  return <section className="activity-panel"><header><div><h3>Audit Log</h3><p>Authenticated user and administrator changes. Player behavior is kept in Screen Events.</p></div>{canExport && <a className="button button--secondary" href={`/api/v1/activity/audit/export.csv?${params}`}><Download size={15} /> Export CSV</a>}</header><div className="activity-table-wrap"><table className="activity-table"><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th><th>Result</th><th>Summary</th><th>Details</th></tr></thead><tbody>{query.data?.items.map((item) => <tr key={item.id}><td><time>{formatWhen(item.timestamp)}</time></td><td><strong>{item.actorName}</strong><small>{item.actorUsername}</small></td><td><strong>{humanize(item.action)}</strong><small>{item.action}</small></td><td><strong><ResourceLink type={item.resourceType} id={item.resourceId} label={item.resourceName || item.resourceId || "—"} /></strong><small>{item.resourceType}</small></td><td><ResultBadge value={item.result} /></td><td>{item.summary}</td><td><TechnicalDetails value={{ requestId: item.requestId, ipAddress: item.ipAddress, ...item.metadata }} /></td></tr>)}</tbody></table></div>{!query.data?.items.length && <EmptyState message="No administrative changes matched these filters." />}<ActivityPagination pagination={pagination} nextCursor={query.data?.nextCursor} /></section>;
}
