package httpapi

import (
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/go-chi/chi/v5/middleware"
	"github.com/tilecast/tilecast/apps/server/internal/web"
)

func (s *server) routes() http.Handler {
	r := chi.NewRouter()
	r.Use(middleware.RequestID)
	r.Use(middleware.Recoverer)
	r.Use(s.securityHeaders)
	r.Use(s.requestLog)
	r.Use(s.restoreGate)
	r.Get("/healthz", s.health)
	r.Get("/readyz", s.ready)
	r.Route("/api/v1", func(api chi.Router) {
		api.Get("/system/health", s.health)
		api.Get("/system/identity", s.systemIdentity)
		api.Get("/auth/status", s.authStatus)
		api.With(s.authRateLimit).Post("/auth/setup", s.setup)
		api.With(s.authRateLimit).Post("/auth/login", s.login)
		api.With(s.requireSession, s.requireCSRF).Post("/auth/logout", s.logout)
		api.With(s.authRateLimit).Post("/auth/mfa/verify", s.verifyMFA)
		api.With(s.authRateLimit).Post("/auth/mfa/passkey/options", s.beginMFAPasskey)
		api.With(s.authRateLimit).Post("/auth/passkey/login/options", s.beginPasskeyLogin)
		api.With(s.authRateLimit).Post("/auth/passkey/login", s.finishPasskeyLogin)

		// Security self-service sits outside the dashboard group because a
		// session waiting on enrollment must still be able to enroll.
		api.Group(func(security chi.Router) {
			security.Use(s.requireSession)
			security.Get("/me/security", s.listFactors)
			security.With(s.requireCSRF).Post("/me/security/totp", s.beginTOTPEnrollment)
			security.With(s.requireCSRF).Post("/me/security/totp/confirm", s.confirmTOTPEnrollment)
			security.With(s.requireCSRF).Post("/me/security/totp/remove", s.disableTOTP)
			security.With(s.requireCSRF).Post("/me/security/recovery-codes", s.regenerateRecoveryCodes)
			security.With(s.requireCSRF).Post("/me/security/passkeys/options", s.beginPasskeyRegistration)
			security.With(s.requireCSRF).Post("/me/security/passkeys", s.finishPasskeyRegistration)
			security.With(s.requireCSRF).Patch("/me/security/passkeys/{id}", s.renamePasskey)
			security.With(s.requireCSRF).Post("/me/security/passkeys/{id}/remove", s.deletePasskey)
		})

		api.With(s.pairingRateLimit).Post("/player/pairing-sessions", s.createPairingSession)
		api.Get("/player/pairing-sessions/{id}", s.pollPairingSession)
		api.With(s.pairingRateLimit).Post("/player/enroll", s.enrollPlayer)
		api.With(s.requireDevice).Post("/player/heartbeat", s.playerHeartbeat)
		api.With(s.requireDevice).Get("/player/socket", s.playerSocket)
		api.With(s.requireDevice).Get("/player/assets/{assetId}/variants/{variantId}", s.playerAssetVariant)
		api.With(s.requireDevice).Head("/player/assets/{assetId}/variants/{variantId}", s.playerAssetVariant)
		api.With(s.requireDevice).Get("/player/manifest", s.playerManifest)
		api.With(s.requireDevice).Get("/player/commands", s.playerCommands)
		api.With(s.requireDevice).Get("/player/config", s.playerConfig)
		api.With(s.requireDevice).Post("/player/commands/{id}/acknowledge", s.acknowledgePlayerCommand)
		api.With(s.requireDevice).Post("/player/commands/{id}/result", s.resultPlayerCommand)
		api.With(s.requireDevice).Get("/player/updates/{releaseId}", s.playerUpdateMetadata)
		api.With(s.requireDevice).Get("/player/updates/{releaseId}/apk", s.playerUpdateArtifact)
		api.With(s.requireDevice).Head("/player/updates/{releaseId}/apk", s.playerUpdateArtifact)
		api.With(s.requireDevice).Get("/player/updates/{releaseId}/artifact", s.playerUpdateArtifact)
		api.With(s.requireDevice).Head("/player/updates/{releaseId}/artifact", s.playerUpdateArtifact)
		api.With(s.requireDevice).Post("/player/update-deployments/{deploymentId}/status", s.playerUpdateStatus)
		api.With(s.operationsRateLimit, s.requireReleasePublisher, s.blockDuringBackup).Post("/player-releases/upload", s.uploadPlayerRelease)

		api.Group(func(dashboard chi.Router) {
			dashboard.Use(s.requireSession)
			dashboard.Use(s.requireEnrollment)
			dashboard.Get("/screens", s.listScreens)
			dashboard.Get("/screens/archive", s.listArchivedScreens)
			dashboard.Get("/screens/{id}", s.getScreen)
			dashboard.Get("/screens/{id}/reliability", s.screenReliability)
			dashboard.Get("/locations", s.listLocations)
			dashboard.Get("/plugins", s.listPlugins)
			dashboard.Get("/plugins/countdown-bar/instances", s.listCountdownBars)
			dashboard.Get("/plugins/countdown-bar/instances/{id}", s.getCountdownBar)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/plugins/countdown-bar/instances", s.createCountdownBar)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/plugins/countdown-bar/instances/{id}", s.updateCountdownBar)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/plugins/countdown-bar/instances/{id}", s.deleteCountdownBar)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/locations", s.createLocation)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Patch("/locations/{id}", s.updateLocation)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/locations/{id}", s.deleteLocation)
			dashboard.Get("/screen-groups", s.listScreenGroups)
			dashboard.Get("/screen-groups/{id}", s.getScreenGroup)
			dashboard.Get("/schedules", s.listSchedules)
			dashboard.Get("/schedules/{id}", s.getSchedule)
			dashboard.Get("/settings", s.getSettings)
			dashboard.With(s.requireRoles("owner", "administrator")).Get("/users", s.listUsers)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/users", s.createUser)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Patch("/users/{id}", s.updateUser)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/users/{id}", s.deleteUser)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/users/{id}/permanent", s.permanentlyDeleteUser)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/users/{id}/security/reset", s.resetUserFactors)
			dashboard.Get("/me/preferences", s.getPreferences)
			dashboard.With(s.requireCSRF).Patch("/me/preferences", s.updatePreferences)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Patch("/settings", s.updateSettings)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/settings/reset", s.resetSettings)
			dashboard.Get("/screen-groups/{id}/policy", s.getGroupPolicy)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/screen-groups/{id}/policy", s.putGroupPolicy)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/screen-groups/{id}/policy", s.deleteGroupPolicy)
			dashboard.Get("/screens/{id}/policy", s.getScreenPolicy)
			dashboard.Get("/screens/{id}/effective-policy", s.getEffectivePolicy)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/screens/{id}/policy", s.putScreenPolicy)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/screens/{id}/policy", s.deleteScreenPolicy)
			dashboard.With(s.requireRoles("owner", "administrator")).Get("/system/status", s.systemStatus)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/system/maintenance/{action}", s.systemMaintenance)
			if s.backups != nil {
				dashboard.With(s.requireRoles("owner")).Get("/system/backups", s.listBackups)
				dashboard.With(s.requireRoles("owner"), s.requireCSRF).Post("/system/backups", s.createBackup)
				dashboard.With(s.requireRoles("owner")).Get("/system/backups/jobs/current", s.currentBackupJob)
				dashboard.With(s.requireRoles("owner")).Get("/system/backups/jobs/{id}", s.getBackupJob)
				dashboard.With(s.requireRoles("owner"), s.requireCSRF).Post("/system/backups/{id}/verify", s.verifyBackup)
				dashboard.With(s.requireRoles("owner")).Get("/system/backups/{id}/plan", s.restorePlan)
				dashboard.With(s.requireRoles("owner"), s.requireCSRF).Post("/system/backups/{id}/restore", s.restoreBackup)
				dashboard.With(s.requireRoles("owner")).Get("/system/backups/{id}/download", s.downloadBackup)
				dashboard.With(s.requireRoles("owner"), s.requireCSRF).Delete("/system/backups/{id}", s.deleteBackup)
			}
			dashboard.With(s.requireRoles("owner")).Get("/system/settings/export", s.exportSettings)
			dashboard.With(s.requireRoles("owner"), s.requireCSRF).Post("/system/settings/import/preview", s.previewSettingsImport)
			dashboard.With(s.requireRoles("owner"), s.requireCSRF).Post("/system/settings/import/apply", s.applySettingsImport)
			dashboard.Get("/takeovers", s.listTakeovers)
			if s.alerts != nil {
				dashboard.Get("/alerts/nws", s.alertSettings)
				dashboard.Get("/alerts/nws/zones", s.alertZones)
				dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/alerts/nws/monitor", s.updateAlertMonitor)
				dashboard.With(s.requireRoles("owner", "administrator"), s.operationsRateLimit, s.requireCSRF).Post("/alerts/nws/poll", s.pollAlerts)
				dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/alerts/nws/rules", s.createAlertRule)
				dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/alerts/nws/rules/{id}", s.updateAlertRule)
				dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/alerts/nws/rules/{id}", s.deleteAlertRule)
			}
			dashboard.Get("/player-releases", s.listPlayerReleases)
			dashboard.With(s.requireRoles("owner"), s.operationsRateLimit, s.requireCSRF).Post("/player-releases/check", s.checkPlayerReleases)
			dashboard.With(s.requireRoles("owner"), s.operationsRateLimit, s.requireCSRF).Post("/player-releases/github/configuration", s.configureGitHubOAuth)
			dashboard.With(s.requireRoles("owner"), s.operationsRateLimit, s.requireCSRF).Post("/player-releases/github/device", s.startGitHubDeviceAuthorization)
			dashboard.With(s.requireRoles("owner"), s.requireCSRF).Post("/player-releases/github/device/poll", s.pollGitHubDeviceAuthorization)
			dashboard.With(s.requireRoles("owner"), s.requireCSRF).Delete("/player-releases/github", s.disconnectGitHub)
			dashboard.With(s.requireRoles("owner"), s.operationsRateLimit, s.requireCSRF, s.blockDuringBackup).Post("/player-releases/{id}/cache", s.cachePlayerRelease)
			dashboard.With(s.requireRoles("owner"), s.operationsRateLimit, s.requireCSRF, s.blockDuringBackup).Delete("/player-releases/{id}", s.deletePlayerRelease)
			dashboard.Get("/update-deployments", s.listUpdateDeployments)
			dashboard.Get("/update-deployments/{id}", s.getUpdateDeployment)
			dashboard.With(s.requireRoles("owner", "administrator"), s.operationsRateLimit, s.requireCSRF).Post("/update-deployments", s.createUpdateDeployment)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/update-deployments/{id}/cancel", s.cancelUpdateDeployment)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/update-deployments/{id}/screens/{screenId}/retry", s.retryUpdateScreen)
			dashboard.Get("/takeovers/{id}", s.getTakeover)
			dashboard.With(s.requireRoles("owner", "administrator"), s.operationsRateLimit, s.requireCSRF).Post("/takeovers", s.activateTakeover)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/takeovers/{id}/cancel", s.cancelTakeover)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screen-groups", s.createScreenGroup)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Patch("/screen-groups/{id}", s.updateScreenGroup)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/screen-groups/{id}", s.deleteScreenGroup)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screen-groups/{id}/screens", s.addScreenGroupMember)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/screen-groups/{id}/screens/{screenId}", s.removeScreenGroupMember)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/screen-groups/{id}/playlist-assignment", s.assignSyncGroupPlaylist)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/screen-groups/{id}/playlist-assignment", s.unassignSyncGroupPlaylist)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/schedules", s.createSchedule)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Patch("/schedules/{id}", s.updateSchedule)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/schedules/{id}", s.deleteSchedule)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/schedules/{id}/enable", s.enableSchedule)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/schedules/{id}/disable", s.disableSchedule)
			dashboard.With(s.requireRoles("owner", "administrator")).Post("/schedules/preview", s.previewSchedule)
			dashboard.Get("/assets", s.listAssets)
			dashboard.Get("/assets/{id}", s.getAsset)
			dashboard.Get("/assets/{id}/website/diagnostics", s.websiteDiagnostics)
			dashboard.Get("/assets/{id}/thumbnail", s.assetThumbnail)
			dashboard.Get("/assets/{id}/preview", s.assetPlaybackPreview)
			dashboard.Head("/assets/{id}/preview", s.assetPlaybackPreview)
			dashboard.Get("/content-folders", s.listContentFolders)
			dashboard.Get("/content-collections", s.listContentCollections)
			dashboard.Get("/content-tags", s.listContentTags)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/content-folders", s.createContentFolder)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/content-folders/{id}", s.updateContentFolder)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Delete("/content-folders/{id}", s.deleteContentFolder)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/content-collections", s.createContentCollection)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/content-collections/{id}", s.updateContentCollection)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Delete("/content-collections/{id}", s.deleteContentCollection)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/content-tags", s.createContentTag)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/content-tags/{id}", s.updateContentTag)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Delete("/content-tags/{id}", s.deleteContentTag)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/assets/bulk-organize", s.bulkOrganizeContent)
			dashboard.Get("/playlists", s.listPlaylists)
			dashboard.Get("/layouts", s.listLayouts)
			dashboard.Get("/layouts/{id}", s.getLayout)
			dashboard.Get("/layouts/{id}/preview-image", s.getLayoutPreviewImage)
			dashboard.Get("/layouts/{id}/revisions", s.listLayoutRevisions)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/layouts", s.createLayout)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/layouts/{id}", s.updateLayout)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Put("/layouts/{id}/preview-image", s.updateLayoutPreviewImage)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Put("/layouts/{id}/draft", s.saveLayoutDraft)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/layouts/{id}/publish", s.publishLayout)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/layouts/{id}/duplicate", s.duplicateLayout)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/layouts/{id}/revisions/{revisionId}/restore", s.restoreLayoutRevision)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Delete("/layouts/{id}", s.deleteLayout)
			dashboard.Get("/playlists/{id}", s.getPlaylist)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/playlists", s.createPlaylist)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/playlists/{id}", s.updatePlaylist)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Delete("/playlists/{id}", s.deletePlaylist)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/playlists/{id}/duplicate", s.duplicatePlaylist)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/playlists/{id}/items", s.addPlaylistItem)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/playlists/{id}/items/{itemId}", s.updatePlaylistItem)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Delete("/playlists/{id}/items/{itemId}", s.deletePlaylistItem)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Put("/playlists/{id}/items/order", s.reorderPlaylistItems)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Put("/playlists/{id}/tag-rule", s.setPlaylistTagRule)
			dashboard.Get("/screens/{id}/playlist-assignment", s.getPlaylistAssignment)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/screens/{id}/playlist-assignment", s.assignPlaylist)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Delete("/screens/{id}/playlist-assignment", s.unassignPlaylist)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/assets/{id}", s.updateAsset)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/assets/websites", s.createWebsite)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/assets/{id}/website", s.updateWebsite)
			// Widgets — renderable visual content.
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/widgets", s.createWidget)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/widgets/compile-preview", s.compileWidgetPreview)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Put("/widgets/{id}/preview-image", s.updateWidgetPreviewImage)
			dashboard.Get("/provider-catalog", s.providerCatalog)
			dashboard.Get("/content-definitions", s.contentDefinitions)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/widgets/{id}", s.updateWidget)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/widgets/{id}/duplicate", s.duplicateWidget)
			// Data Sources — reusable non-visual data connections.
			dashboard.Get("/data-sources", s.listDataSources)
			dashboard.Get("/data-sources/{id}", s.getDataSource)
			dashboard.Get("/data-sources/{id}/preview", s.previewSavedDataSource)
			dashboard.Get("/data-sources/{id}/diagnostics", s.dataSourceDiagnostics)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.operationsRateLimit).Get("/data-sources/{id}/inspect", s.inspectSavedDataSource)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/data-sources", s.createDataSource)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Patch("/data-sources/{id}", s.updateDataSource)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/data-sources/{id}/duplicate", s.duplicateDataSource)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Delete("/data-sources/{id}", s.deleteDataSource)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.operationsRateLimit, s.requireCSRF).Post("/data-sources/{provider}/preview", s.previewDataSource)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.operationsRateLimit, s.requireCSRF).Post("/data-sources/{provider}/inspect", s.inspectDataSource)
			// Form Data Sources. Reads are session-guarded and further authorized per-form inside
			// each handler (grants depend on the {id} path param); mutations add CSRF. Creating a
			// form requires the editor+ global role; the creator becomes its manager.
			if s.forms != nil {
				dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF).Post("/forms", s.createForm)
				dashboard.Get("/forms", s.listForms)
				dashboard.Get("/data-sources/{id}/form", s.getForm)
				dashboard.With(s.requireCSRF).Patch("/data-sources/{id}/form", s.updateFormMetadata)
				dashboard.With(s.requireCSRF).Patch("/data-sources/{id}/form/draft", s.updateFormDraft)
				dashboard.With(s.requireCSRF).Post("/data-sources/{id}/form/publish", s.publishForm)
				dashboard.With(s.requireCSRF).Put("/data-sources/{id}/form/workflow", s.configureFormWorkflow)
				dashboard.Get("/data-sources/{id}/records", s.listFormRecords)
				dashboard.With(s.requireCSRF).Post("/data-sources/{id}/records", s.createFormRecord)
				dashboard.Get("/data-sources/{id}/records/{recordId}", s.getFormRecord)
				dashboard.With(s.requireCSRF).Patch("/data-sources/{id}/records/{recordId}", s.updateFormRecord)
				dashboard.With(s.requireCSRF).Delete("/data-sources/{id}/records/{recordId}", s.deleteFormRecord)
				dashboard.With(s.requireCSRF).Post("/data-sources/{id}/records/{recordId}/transitions", s.transitionFormRecord)
				dashboard.With(s.requireCSRF).Post("/data-sources/{id}/records/{recordId}/comments", s.addFormRecordComment)
				dashboard.With(s.requireCSRF).Post("/data-sources/{id}/records/{recordId}/attachments", s.uploadFormRecordAttachment)
				dashboard.Get("/data-sources/{id}/records/{recordId}/attachments/{attachmentId}/content", s.serveFormRecordAttachment)
				dashboard.With(s.requireCSRF).Delete("/data-sources/{id}/records/{recordId}/attachments/{attachmentId}", s.removeFormRecordAttachment)
				dashboard.Get("/data-sources/{id}/views", s.listFormViews)
				dashboard.With(s.requireCSRF).Put("/data-sources/{id}/views", s.upsertFormView)
				dashboard.With(s.requireCSRF).Post("/data-sources/{id}/views/preview", s.previewFormView)
				dashboard.With(s.requireCSRF).Delete("/data-sources/{id}/views/{viewId}", s.deleteFormView)
				dashboard.Get("/data-sources/{id}/outputs", s.getFormOutputs)
				dashboard.With(s.requireCSRF).Post("/data-sources/{id}/outputs/rebuild", s.rebuildFormOutputs)
				dashboard.Get("/data-sources/{id}/grants", s.listFormGrants)
				dashboard.With(s.requireCSRF).Put("/data-sources/{id}/grants", s.setFormGrant)
				dashboard.With(s.requireCSRF).Delete("/data-sources/{id}/grants/{grantId}", s.revokeFormGrant)
				dashboard.Get("/data-sources/{id}/access", s.listFormAccess)
				dashboard.With(s.requireCSRF).Put("/data-sources/{id}/access/{userId}", s.replaceFormGrants)
				dashboard.Get("/data-sources/{id}/user-directory", s.searchFormUsers)
				dashboard.Get("/approvals", s.listApprovals)
			}
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF, s.blockDuringBackup).Delete("/assets/{id}", s.deleteAsset)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF, s.blockDuringBackup).Post("/assets/{id}/retry", s.retryAsset)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF, s.blockDuringBackup).Post("/uploads", s.createUpload)
			dashboard.Head("/uploads/{id}", s.headUpload)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF, s.blockDuringBackup).Patch("/uploads/{id}", s.patchUpload)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF, s.blockDuringBackup).Post("/uploads/{id}/complete", s.completeUpload)
			dashboard.With(s.requireRoles("owner", "administrator", "editor"), s.requireCSRF, s.blockDuringBackup).Delete("/uploads/{id}", s.cancelUpload)
			dashboard.With(s.requireRoles("owner", "administrator")).Get("/system/media-diagnostics", s.mediaDiagnostics)
			dashboard.With(s.requireRoles("owner", "administrator")).Get("/screens/pairing/pending", s.listPendingPairings)
			dashboard.With(s.codeRateLimit).Post("/screens/pairing/resolve", s.resolvePairing)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screens/pairing/{id}/approve", s.approvePairing)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screens/pairing/{id}/reject", s.rejectPairing)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Patch("/screens/{id}", s.updateScreen)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screens/{id}/disable", s.disableScreen)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screens/{id}/enable", s.enableScreen)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screens/{id}/revoke", s.revokeScreen)
			dashboard.Get("/screens/{id}/commands", s.listScreenCommands)
			dashboard.With(s.requireRoles("owner", "administrator"), s.operationsRateLimit, s.requireCSRF).Post("/screens/{id}/commands", s.createPlayerCommand)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Post("/screens/{id}/commands/{commandId}/cancel", s.cancelPlayerCommand)
			dashboard.With(s.requireRoles("owner", "administrator"), s.requireCSRF).Put("/screens/{id}/power-assist", s.confirmPowerAssist)
		})
	})
	r.Handle("/*", web.Handler())
	return r
}
